In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import random
get_ipython().run_line_magic('matplotlib', 'inline')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score,KFold,StratifiedKFold, GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,average_precision_score,recall_score,roc_auc_score
from sklearn.preprocessing import RobustScaler,StandardScaler,LabelEncoder,MinMaxScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.feature_selection import SelectKBest,chi2

from keras.models import Sequential
from keras.layers import Activation,BatchNormalization
from keras.layers.core import Dense,Dropout
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.callbacks import ReduceLROnPlateau,EarlyStopping
Data=pd.read_csv("Phishing.csv",header="infer")

In [60]:
x=Data.iloc [:,1:-1]
x=x.values
y=Data.iloc[:,-1].values

In [61]:
from sklearn import preprocessing
x1= preprocessing.normalize(x)

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.20,random_state=42)

# Decision tree

In [63]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
clf_gini=DecisionTreeClassifier(criterion="gini", random_state=100,max_depth=3, min_samples_leaf=5)
clf_gini.fit(x_train, y_train)
Y_pred=clf_gini.predict(x_test)
from sklearn import metrics
#metrics.accuracy_score(y_test,Y_pred)*100 

In [64]:
import math
train_pred1=clf_gini.predict(x_train)
test_pred1=clf_gini.predict(x_test)
#print(train_pred1)
#print(test_pred1)

In [65]:
import math
train_pred1=clf_gini.predict(x_train)
test_pred1=clf_gini.predict(x_test)

confusion_matrix_train1 = []
confusion_matrix_train1=confusion_matrix(y_train,train_pred1)
TP1 = confusion_matrix_train1[1,1]
TN1 = confusion_matrix_train1[0,0]
FP1 = confusion_matrix_train1[0,1]
FN1 = confusion_matrix_train1[1,0]

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)

confusion_matrix_test1 = []
confusion_matrix_test1=confusion_matrix(y_test,test_pred1)
TP1 = confusion_matrix_test1[1,1]
TN1 = confusion_matrix_test1[0,0]
FP1 = confusion_matrix_test1[0,1]
FN1 = confusion_matrix_test1[1,0]
Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)


Accuracy :  90.63772048846675
Sensitivity :  90.90167278661771
Specificity :  90.30948756976154
F1 score :  91.49897330595482
Mattews correlation coefficient :  81.0909287924864
Accuracy :  91.40660334690185
Sensitivity :  92.11155378486056
Specificity :  90.48117154811716
F1 score :  92.40607513988809
Mattews correlation coefficient :  82.51271212073331


In [66]:
'''import pydotplus
from sklearn.tree import export_graphviz
from IPython.display import Image
dot_data=tree.export_graphviz(clf_gini)
graph=pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())'''


'import pydotplus\nfrom sklearn.tree import export_graphviz\nfrom IPython.display import Image\ndot_data=tree.export_graphviz(clf_gini)\ngraph=pydotplus.graph_from_dot_data(dot_data)\nImage(graph.create_png())'

In [67]:
'''from sklearn.metrics import accuracy_score'''

'from sklearn.metrics import accuracy_score'

In [68]:
'''maxdepths=[3,4,5,6,7,8,9,10,11,15,20,25,30,35,40,45,50,60]# alist contains
trainAcc=np.zeros(len(maxdepths))
testAcc=np.zeros(len(maxdepths))'''

'maxdepths=[3,4,5,6,7,8,9,10,11,15,20,25,30,35,40,45,50,60]# alist contains\ntrainAcc=np.zeros(len(maxdepths))\ntestAcc=np.zeros(len(maxdepths))'

In [69]:
'''index=0
for depth in maxdepths:
    clf=tree.DecisionTreeClassifier(max_depth=depth)
    clf=clf.fit(x_train,y_train)
    y_predTrain=clf.predict(x_train)
    y_predTest=clf.predict(x_test)
    trainAcc[index]=accuracy_score(y_train,y_predTrain)
    testAcc[index]=accuracy_score(y_test,y_predTest)
    index +=1'''

'index=0\nfor depth in maxdepths:\n    clf=tree.DecisionTreeClassifier(max_depth=depth)\n    clf=clf.fit(x_train,y_train)\n    y_predTrain=clf.predict(x_train)\n    y_predTest=clf.predict(x_test)\n    trainAcc[index]=accuracy_score(y_train,y_predTrain)\n    testAcc[index]=accuracy_score(y_test,y_predTest)\n    index +=1'

In [70]:
'''plt.plot(maxdepths,trainAcc,'ro-',maxdepths,testAcc,'bv--')
plt.legend(['Training Accuracy','Test Accuracy'])
plt.xlabel('Max Depth')
plt.ylabel('Accuracy')'''

"plt.plot(maxdepths,trainAcc,'ro-',maxdepths,testAcc,'bv--')\nplt.legend(['Training Accuracy','Test Accuracy'])\nplt.xlabel('Max Depth')\nplt.ylabel('Accuracy')"

In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [72]:
Data.isnull()
Data.isnull().sum()

having_IP_Address              0
URL_Length                     0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result    

In [73]:
pd.options.display.max_columns=None

# Linear Regression

In [74]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
from sklearn import metrics
metrics.accuracy_score(y_test,Y_pred)*100 

91.40660334690185

In [75]:
import math
train_pred1=regressor.predict(x_train)
test_pred1=regressor.predict(x_test)
#print(train_pred1)
train_pred1 = np.where(train_pred1 > 0.0, 1, -1)
#print(train_pred1)
#print(test_pred1)
test_pred1 = np.where(test_pred1 > 0.0, 1, -1)
#print(test_pred1)

In [76]:
import math
train_pred1=regressor.predict(x_train)
test_pred1=regressor.predict(x_test)

train_pred1 = np.where(train_pred1 > 0.0, 1, -1)

confusion_matrix_train1 = []
confusion_matrix_train1=confusion_matrix(y_train,train_pred1)
print(confusion_matrix_train1)
TP1 = confusion_matrix_train1[1,1]
TN1 = confusion_matrix_train1[0,0]
FP1 = confusion_matrix_train1[0,1]
FN1 = confusion_matrix_train1[1,0]

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)


test_pred1 = np.where(test_pred1 > 0.0, 1, -1)

confusion_matrix_test1 = []
confusion_matrix_test1=confusion_matrix(y_test,test_pred1)
print(confusion_matrix_test1)
TP1 = confusion_matrix_test1[1,1]
TN1 = confusion_matrix_test1[0,0]
FP1 = confusion_matrix_test1[0,1]
FN1 = confusion_matrix_test1[1,0]
Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)

[[3521  421]
 [ 282 4620]]
Accuracy :  92.05110809588422
Sensitivity :  94.24724602203183
Specificity :  89.32014205986809
F1 score :  92.9296992859298
Mattews correlation coefficient :  83.89967536564993
[[ 844  112]
 [  62 1193]]
Accuracy :  92.13025780189959
Sensitivity :  95.0597609561753
Specificity :  88.28451882845188
F1 score :  93.203125
Mattews correlation coefficient :  83.95706585407933


In [77]:
#Data = pd.DataFrame({'Actual':y_test.flatten(),'Predicted':y_pred.flatten()})

In [78]:
'''
df1 = Data.head(40)
df1.plot(kind='bar',figsize=(16,10))
plt.grid(which='major', linestyle='-', linewidth='0.5', color='green')
plt.grid(which='minor', linestyle=':', linewidth='0.5', color='black')
plt.show()
'''


"\ndf1 = Data.head(40)\ndf1.plot(kind='bar',figsize=(16,10))\nplt.grid(which='major', linestyle='-', linewidth='0.5', color='green')\nplt.grid(which='minor', linestyle=':', linewidth='0.5', color='black')\nplt.show()\n"

In [79]:
'''from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))'''

"from sklearn import metrics\nprint('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))\nprint('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))\nprint('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))"

In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import random
get_ipython().run_line_magic('matplotlib', 'inline')

# K-Nearest Neighbors

In [81]:
pd.options.display.max_columns=None
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')
numNeighbours=[1,5,10,15,20,25,30]
trainAcc=[]
testAcc=[]

In [82]:
train_tp = []
train_tn = []
train_fp = []
trian_fn = []


test_tp = []
test_tn = []
test_fp = []
test_fn = []



for k in numNeighbours:
    clf=KNeighborsClassifier(n_neighbors=k, metric='minkowski',p=2)
    clf.fit(x_train,y_train)
    
    y_predTrain=clf.predict(x_train)
    confusion_matrix_train1 = []
    confusion_matrix_train1=confusion_matrix(y_train,y_predTrain)
    #print(confusion_matrix_train1)
    train_tp.append(confusion_matrix_train1[1,1])
    train_tn.append(confusion_matrix_train1[0,0])
    train_fp.append(confusion_matrix_train1[0,1])
    trian_fn.append(confusion_matrix_train1[1,0])
    #Accuracy=((train_tp+train_tn)/float(train_tp+train_tn+train_fp+trian_fn))  ##Accuracy
    #print("Accuracy : ",Accuracy*100)
    
    y_predTest=clf.predict(x_test)
    confusion_matrix_test1 = []
    confusion_matrix_test1=confusion_matrix(y_test,y_predTest)
    #print(confusion_matrix_test1)
    test_tp.append(confusion_matrix_test1[1,1])
    test_tn.append(confusion_matrix_test1[0,0])
    test_fp.append(confusion_matrix_test1[0,1])
    test_fn.append(confusion_matrix_test1[1,0])
    
    trainAcc.append(accuracy_score(y_train,y_predTrain))
    testAcc.append(accuracy_score(y_test,y_predTest))
    
'''
print(train_tp)
print(train_tn)
print(train_fp)
print(trian_fn)
print(test_tp)
print(test_tn)
print(test_fp)
print(test_fn)
'''    



'\nprint(train_tp)\nprint(train_tn)\nprint(train_fp)\nprint(trian_fn)\nprint(test_tp)\nprint(test_tn)\nprint(test_fp)\nprint(test_fn)\n'

In [83]:
from statistics import mean
TP1 = mean(train_tp)
TN1 = mean(train_tn)
FP1 = mean(train_fp)
FN1 = mean(trian_fn)

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)


TP1 = mean(test_tp)
TN1 = mean(test_tn)
FP1 = mean(test_fp)
FN1 = mean(test_fn)

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)


Accuracy :  94.93327301515494
Sensitivity :  95.91920016323199
Specificity :  93.70718091854859
F1 score :  95.4517766497462
Mattews correlation coefficient :  89.73885022114868
Accuracy :  93.43891402714932
Sensitivity :  95.0597609561753
Specificity :  91.30890052356021
F1 score :  94.27103911497431
Mattews correlation coefficient :  86.61257740227852


# Random Forest  

In [89]:
classifier = RandomForestClassifier(n_estimators = 10)
classifier.fit(x_train, y_train)

y_predTrain = classifier.predict(x_train)

confusion_matrix_train1 = []
confusion_matrix_train1=confusion_matrix(y_train,y_predTrain)

print(confusion_matrix_train1)
TP1 = confusion_matrix_train1[1,1]
TN1 = confusion_matrix_train1[0,0]
FP1 = confusion_matrix_train1[0,1]
FN1 = confusion_matrix_train1[1,0]

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)


y_predTest=classifier.predict(x_test)

confusion_matrix_test1 = []
confusion_matrix_test1=confusion_matrix(y_test,y_predTest)

print(confusion_matrix_test1)
TP1 = confusion_matrix_test1[1,1]
TN1 = confusion_matrix_test1[0,0]
FP1 = confusion_matrix_test1[0,1]
FN1 = confusion_matrix_test1[1,0]

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)

[[3869   73]
 [  38 4864]]
Accuracy :  98.7449118046133
Sensitivity :  99.2248062015504
Specificity :  98.14814814814815
F1 score :  98.87183656875699
Mattews correlation coefficient :  97.46081553273393
[[ 902   54]
 [  31 1224]]
Accuracy :  96.15558570782451
Sensitivity :  97.52988047808765
Specificity :  94.35146443514645
F1 score :  96.64429530201343
Mattews correlation coefficient :  92.16624708352609


# Support Vector Machine

In [86]:
from sklearn.svm import SVC

In [90]:
classifier = SVC(kernel = 'rbf', probability=True, random_state=0, gamma=0.1, C=1.0)
classifier.fit(x_train, y_train)

y_predTrain = classifier.predict(x_train)

confusion_matrix_train1 = []
confusion_matrix_train1=confusion_matrix(y_train,y_predTrain)

print(confusion_matrix_train1)
TP1 = confusion_matrix_train1[1,1]
TN1 = confusion_matrix_train1[0,0]
FP1 = confusion_matrix_train1[0,1]
FN1 = confusion_matrix_train1[1,0]

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)


y_predTest=classifier.predict(x_test)

confusion_matrix_test1 = []
confusion_matrix_test1=confusion_matrix(y_test,y_predTest)

print(confusion_matrix_test1)
TP1 = confusion_matrix_test1[1,1]
TN1 = confusion_matrix_test1[0,0]
FP1 = confusion_matrix_test1[0,1]
FN1 = confusion_matrix_test1[1,0]

Accuracy=((TP1+TN1)/float(TP1+TN1+FP1+FN1))  ##Accuracy
Sensitivity=(TP1/float(TP1+FN1))             ##Sensitivity
Specificity=(TN1/float(TN1+FP1))             ##Specificity
F1=((2*TP1)/float((2*TP1)+FP1+FN1))     ## F1 score
sqr1 = (TP1+FP1)*(TP1+FN1)*(TN1+FP1)*(TN1+FN1)
MCC=(((TP1*TN1)-(FP1*FN1))/math.sqrt(sqr1)) ##Mattews correlation coefficient
print("Accuracy : ",Accuracy*100)
print("Sensitivity : ",Sensitivity*100)
print("Specificity : ",Specificity*100)
print("F1 score : ",F1*100)
print("Mattews correlation coefficient : ",MCC*100)

[[3523  419]
 [ 255 4647]]
Accuracy :  92.37901402080506
Sensitivity :  94.79804161566707
Specificity :  89.37087772704211
F1 score :  93.23836276083468
Mattews correlation coefficient :  84.57327435598869
[[ 855  101]
 [  56 1199]]
Accuracy :  92.8991406603347
Sensitivity :  95.5378486055777
Specificity :  89.43514644351464
F1 score :  93.85518590998043
Mattews correlation coefficient :  85.52653363066133
